/* GENERATED by tools/tflite_to_c.py. Do not edit. */
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

extern const unsigned char g_model_xs[];
extern const unsigned int g_model_xs_len;
extern const unsigned char g_model_s[];
extern const unsigned int g_model_s_len;
extern const unsigned char g_model_m[];
extern const unsigned int g_model_m_len;

#endif
