/* GENERATED by tools/tflite_to_c.py from ml/artifacts. Do not edit. */
#ifndef MODEL_META_H
#define MODEL_META_H

#define KWS_KEYWORD        "marvin"
#define KWS_N_FRAMES       98
#define KWS_N_CLASSES      3
#define KWS_CLASS_KEY      2
#define KWS_NORM_MEAN      15.139422416687012f
#define KWS_NORM_STD       5.25802755355835f

#endif
