/* GENERATED by tools/gen_dsp_tables.py from ml/feature_config.py. Do not edit. */
#ifndef DSP_TABLES_H
#define DSP_TABLES_H
#include <stdint.h>

#define FEAT_FS         16000
#define FEAT_WIN        480
#define FEAT_HOP        160
#define FEAT_NFFT       512
#define FEAT_N_BINS     257
#define FEAT_N_MELS     40
#define FEAT_PREEMPH    0.97f
#define FEAT_LOG_FLOOR  1.0f
#define MEL_NNZ         493

extern const float    g_hamming[FEAT_WIN];
extern const uint16_t g_mel_start[FEAT_N_MELS];
extern const uint16_t g_mel_len[FEAT_N_MELS];
extern const float    g_mel_w[MEL_NNZ];

#endif
