"""Generate firmware/src/dsp/dsp_tables.{h,c} from the Python reference (ml/features.py).

Run from the repo root: python tools/gen_dsp_tables.py
Emits the config #defines, the Hamming window, and the mel filterbank in sparse form
(each triangular filter is contiguous: start bin, length, weights).
"""
import pathlib, sys
import numpy as np

root = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root / "ml"))
import feature_config as c
import features as f

out = root / "firmware" / "src" / "dsp"
out.mkdir(parents=True, exist_ok=True)

M = f.mel_matrix().astype(np.float32)
start, length, weights = [], [], []
for row in M:
    nz = np.nonzero(row)[0]
    assert len(nz) and nz[-1] - nz[0] + 1 == len(nz), "mel filter not contiguous"
    start.append(int(nz[0])); length.append(len(nz)); weights.extend(row[nz].tolist())

def fl(v):  # exact float32 round-trip
    return repr(float(np.float32(v))) + "f" if np.isfinite(v) else "0.0f"

def arr(vals, per_line=6):
    v = [fl(x) for x in vals]
    return ",\n".join("    " + ", ".join(v[i:i + per_line]) for i in range(0, len(v), per_line))

h = f"""/* GENERATED by tools/gen_dsp_tables.py from ml/feature_config.py. Do not edit. */
#ifndef DSP_TABLES_H
#define DSP_TABLES_H
#include <stdint.h>

#define FEAT_FS         {c.FS}
#define FEAT_WIN        {c.WIN}
#define FEAT_HOP        {c.HOP}
#define FEAT_NFFT       {c.NFFT}
#define FEAT_N_BINS     {c.N_BINS}
#define FEAT_N_MELS     {c.N_MELS}
#define FEAT_PREEMPH    {c.PREEMPH}f
#define FEAT_LOG_FLOOR  {c.LOG_FLOOR}f
#define MEL_NNZ         {len(weights)}

extern const float    g_hamming[FEAT_WIN];
extern const uint16_t g_mel_start[FEAT_N_MELS];
extern const uint16_t g_mel_len[FEAT_N_MELS];
extern const float    g_mel_w[MEL_NNZ];

#endif
"""
src = f"""/* GENERATED by tools/gen_dsp_tables.py from ml/features.py. Do not edit. */
#include "dsp_tables.h"

const float g_hamming[FEAT_WIN] = {{
{arr(f.hamming())}
}};

const uint16_t g_mel_start[FEAT_N_MELS] = {{ {", ".join(map(str, start))} }};
const uint16_t g_mel_len[FEAT_N_MELS] = {{ {", ".join(map(str, length))} }};

const float g_mel_w[MEL_NNZ] = {{
{arr(weights)}
}};
"""
(out / "dsp_tables.h").write_text(h, newline="\n")
(out / "dsp_tables.c").write_text(src, newline="\n")
print(f"wrote {out}: {c.N_MELS} filters, {len(weights)} non-zero weights, "
      f"flash ~{(c.WIN + len(weights)) * 4 + c.N_MELS * 4} B")
