"""Embed the int8 .tflite models (and normalisation constants) as C arrays.

python tools/tflite_to_c.py            # writes firmware/src/model/model_<variant>.c and model_meta.h

The firmware links exactly one model_<variant>.c (Makefile MODEL=xs|s|m). Quantisation scale /
zero-point of the input and output tensors are read from the model at run time; only the
feature normalisation (train mean/std) is baked into model_meta.h.
"""
import json, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root / "ml"))
import model_config as mc

art = mc.ARTIFACTS
out = root / "firmware" / "src" / "model"
out.mkdir(parents=True, exist_ok=True)
norm = json.loads((art / f"{mc.KEYWORD}_norm.json").read_text())

for v in mc.VARIANTS:
    blob = (art / f"{mc.KEYWORD}_{v}_int8.tflite").read_bytes()
    body = ",\n".join("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16))
    (out / f"model_{v}.c").write_text(
        f"/* GENERATED by tools/tflite_to_c.py from ml/artifacts/{mc.KEYWORD}_{v}_int8.tflite. Do not edit. */\n"
        f"#include \"model_data.h\"\n\n"
        f"const unsigned char g_model_{v}[] __attribute__((aligned(16))) = {{\n{body}\n}};\n"
        f"const unsigned int g_model_{v}_len = {len(blob)};\n", newline="\n")
    print(f"model_{v}.c: {len(blob)} bytes")

decl = "\n".join(f"extern const unsigned char g_model_{v}[];\nextern const unsigned int g_model_{v}_len;" for v in mc.VARIANTS)
(out / "model_data.h").write_text(
    "/* GENERATED by tools/tflite_to_c.py. Do not edit. */\n#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n"
    f"{decl}\n\n#endif\n", newline="\n")

(out / "model_meta.h").write_text(
    "/* GENERATED by tools/tflite_to_c.py from ml/artifacts. Do not edit. */\n#ifndef MODEL_META_H\n#define MODEL_META_H\n\n"
    f"#define KWS_KEYWORD        \"{mc.KEYWORD}\"\n"
    f"#define KWS_N_FRAMES       {mc.N_FRAMES}\n"
    f"#define KWS_N_CLASSES      {len(mc.CLASSES)}\n"
    f"#define KWS_CLASS_KEY      {mc.KEY}\n"
    f"#define KWS_NORM_MEAN      {norm['mean']!r}f\n"
    f"#define KWS_NORM_STD       {norm['std']!r}f\n\n#endif\n", newline="\n")
print("wrote model_data.h, model_meta.h")
